services:
  ### APP

  ### POSTGRES
  db:
    container_name: postgresql-16-fearflix
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - fearflix-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin1strator
      - POSTGRES_PASSWORD=sup3rus3r
      - POSTGRES_DB=fearflix_db

  ### ELASTICSEARCH
  es:
    container_name: elasticsearch-9-fearflix
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=false
      - ELASTIC_PASSWORD=sup3rus3relastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1024m
    volumes:
      - fearflix-es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  ### KIBANA
  kibana:
    container_name: kibana-8-fearflix
    image: docker.elastic.co/kibana/kibana:9.2.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - XPACK_FLEET_ENABLED=false
      - XPACK_FLEET_AGENTS_ENABLED=false
      - XPACK_FLEET_AGENTS_FLEET_SERVER_ENABLED=false
    env_file:
      - .env.kibana
    ports:
      - "5601:5601"
    depends_on:
      - es

  ### MESSAGING
  rabbitmq:
    container_name: rabbitmq-fearlflix
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15627"
    env_file:
      - .env.rabbitmq

volumes:
  fearflix-db-data:
  fearflix-es-data:
